In [16]:
import numpy as np
a=[np.random.randn(5),np.random.randn(1,10),np.random.randn(50,1)
,np.random.randn(50,1),np.random.randn(40,1),np.random.randn(10,1)]

In [17]:
a[0]

array([-1.23175844,  1.06825554,  2.06700288,  0.97166881,  0.18088736])

In [15]:
a[1]

array([[ 0.57824681, -0.43469256, -0.5830539 ,  0.68399669, -1.48266257,
        -0.4073107 ,  0.11330619, -0.59003024, -0.05478912,  1.18546246]])

In [8]:
np.random.randn(1,20)

array([[-0.56045077,  1.79342473,  0.0802338 ,  1.13423156,  0.84437143,
        -0.08007642,  0.63027943, -1.69090346,  1.36005658, -1.86390888,
         0.26211557, -0.60200188, -0.47897782,  1.92731568, -1.28856652,
         0.01062463,  0.61723952,  0.01746447, -1.26356173, -1.11024412]])

In [33]:
import random
random.uniform(4,9)

7.579537343826878

In [35]:
random.sample(range(0,10),10)

[5, 6, 1, 3, 8, 4, 9, 2, 7, 0]

In [38]:
random.sample(range(10,30),10)

[12, 28, 21, 11, 24, 29, 15, 16, 10, 27]

In [39]:
random.sample(range(5,20),10)

[16, 9, 18, 13, 14, 15, 10, 17, 8, 11]

In [40]:
random.sample(range(10,20),10)

[10, 16, 14, 19, 12, 11, 13, 17, 18, 15]

In [41]:
random.sample(range(5,15),10)

[9, 7, 6, 5, 13, 14, 11, 8, 10, 12]

In [82]:
random.sample(range(1,11),15)

ValueError: Sample larger than population or is negative

In [76]:
import pandas as pd
a=random.sample(range(0,10),10),random.sample(range(10,30),10),random.sample(range(5,20),10),random.sample(range(7,20),10),random.sample(range(5,15),10),random.sample(range(1,11),10)
df=pd.DataFrame(a)
df=df.transpose()
df.rename(columns={0:'Bus',1:'Car',2:'Motor Cycle',3:'Person',4:'Rickshaw',5:'Truck'})

SyntaxError: invalid syntax (<ipython-input-79-74b769b7016d>, line 1)

Bus  Car  Motor Cycle  Person  Rickshaw  Truck
0    6   10           19       9         9      1
1    1   17            5      16         5      8
2    2   13           11      18        14      2
3    3   19            9      13        10      4
4    0   26           10      19         8      7
5    7   24           13      14         7      9
6    8   29           16       8        13      3
7    5   27           18      10        11     10
8    4   23            8       7        12      6
9    9   16            7      17         6      5

In [60]:
labels = 'Bus', 'Car', 'Motor Cycle', 'Person','Rickshaw','Truck'
chart_data = pd.DataFrame(a,columns=labels)

ValueError: 6 columns passed, passed data had 10 columns

In [52]:
np.random.randn(10,6)

array([[-0.94562406,  0.32805649, -1.70986216,  0.17905004, -1.14029852,
         1.39447897],
       [ 0.51254088, -1.26443243, -0.50303416, -0.97820634,  2.70918487,
        -0.20738857],
       [ 0.45192537,  0.35938381,  0.39182746, -0.34718939,  0.92932668,
         0.83095203],
       [-0.71005677,  1.06550458, -0.51847491, -2.07285274,  1.11648547,
        -0.94388363],
       [ 0.70335451, -0.25656571,  1.89482348,  0.59165966, -0.9620955 ,
         0.48414733],
       [ 0.10596912,  0.2582604 , -3.07423489,  0.89607293, -1.18607018,
        -0.06982222],
       [ 1.30072961, -0.03096148, -0.02498688, -0.39994097,  0.72760551,
         0.3915336 ],
       [-0.63923634,  0.67150557, -0.07352769, -0.03957809, -0.57747267,
        -0.36143712],
       [-1.38650373,  0.36638711,  0.34758836, -0.26746778,  2.14188527,
        -0.37033189],
       [-0.72728983,  0.67549658, -2.59179784,  1.22167932,  1.72986611,
         1.04242417]])

In [102]:
a= [random.randrange(0,5,1) for i in range (10)],[random.randrange(1,10,1) for i in range (10)], [random.randrange(1,6,1) for i in range (10)],[random.randrange(1,8,1) for i in range (10)], [random.randrange(1,6,1) for i in range (10)],[random.randrange(1,5,1) for i in range (10)]
df=pd.DataFrame(a).transpose().rename(columns={0:'Bus',1:'Car',2:'Motor Cycle',3:'Person',4:'Rickshaw',5:'Truck'})


In [103]:
df

Bus  Car  Motor Cycle  Person  Rickshaw  Truck
0    2    6            3       4         3      3
1    0    7            2       1         1      4
2    0    4            3       5         5      4
3    3    2            5       6         2      2
4    1    5            5       3         1      4
5    0    9            4       2         1      2
6    2    9            1       6         5      2
7    0    1            1       2         4      2
8    1    8            2       6         3      4
9    2    4            2       7         3      2

In [98]:
df

Bus  Car  Motor Cycle  Person  Rickshaw  Truck
0    3    3            3       4         4      1
1    2    3            4       3         4      3
2    2    2            2       4         2      1
3    2    4            2       2         2      3
4    3    4            1       1         2      1
5    3    2            3       1         2      3
6    3    2            3       4         3      4
7    1    2            2       4         4      4
8    1    4            1       2         3      4
9    3    4            3       4         1      1

In [110]:
traffic=[500]

In [122]:
random.randrange(0,traffic[-1]//2,1)

239

In [123]:
traffic=[2,4]

In [125]:
traffic[-2]

2

In [126]:
5//2

2

In [127]:
round(5.999999999999999999999)

6